- name: Deploy Servers
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: Create User
      user:
        state: present
        shell: /bin/bash
        name: yen
        password: "{{ 'Password1' | password_hash('sha512') }}"
        update_password: on_create
    - name: sudo
      copy:
        dest: /etc/sudoers.d/yen
        content: "yen ALL=(root) NOPASSWD: ALL"
    - name: edit sshd
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        insertafter: '^PasswordAuthentication'
      notify: restart_sshd
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
